version: '3'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.1
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
      #- MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
      - MLFLOW_ARTIFACT_ROOT=s3://${BUCKET_NAME}/${ARTIFACT_PATH}/
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=https://eu2.contabostorage.com
      - AWS_DEFAULT_REGION=eu-central-2
    volumes:
      - ./mlflow_data:/mlflow
   # command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
   # command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root s3://eu2.contabostorage.com/bucket/mlflow/
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root s3://${BUCKET_NAME}/${ARTIFACT_PATH}/

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # Mounting nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html:ro   # Mounting index.html
    depends_on:
      - mlflow

  mlflow_app:
    build: ./app
    container_name: mlflow_app
    depends_on:
      - mlflow


